name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - 'crates/**'
      - 'Cargo.*'
      - 'Makefile'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [main]
    paths:
      - 'crates/**'
      - 'Cargo.*'
      - 'Makefile'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always
  # Test environment configuration
  RPC_URL: http://127.0.0.1:8899
  TEST_SERVER_URL: http://127.0.0.1:8080
  KORA_PRIVATE_KEY: 64TVMxZyYyLHwyfZRJUJMqF8GJsMsZQKk4JhdKkyMB7k3fNUjWZdAF1YmyLd43dWEBLCLYjKDkoRGfMwMoGUrDF6
  KORA_CONFIG_FILE: kora.toml
  VALIDATOR_PORT: 8899
  KORA_RPC_PORT: 8080
  VALIDATOR_TIMEOUT: 60
  KORA_TIMEOUT: 30
  RUST_LOG: info

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: make check
      - name: Run clippy
        run: make lint
      - name: Run tests
        run: make test
      - name: Build
        run: make build

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Setup Solana CLI
        uses: ./.github/actions/setup-solana

      - name: Setup Solana test validator
        uses: ./.github/actions/setup-solana-validator
        with:
          rpc-url: ${{ env.RPC_URL }}
          timeout: ${{ env.VALIDATOR_TIMEOUT }}

      - name: Build Kora RPC server
        run: make build

      - name: Start Kora RPC server
        run: |
          echo "🚀 Starting Kora RPC server..."
          cargo run -p kora-rpc --bin kora-rpc -- \
            --private-key ${{ env.KORA_PRIVATE_KEY }} \
            --config ${{ env.KORA_CONFIG_FILE }} \
            --rpc-url ${{ env.RPC_URL }} \
            --port ${{ env.KORA_RPC_PORT }} \
            &
          KORA_PID=$!
          echo "KORA_PID=$KORA_PID" >> $GITHUB_ENV

          # Wait for Kora RPC server to be ready
          echo "⏳ Waiting for Kora RPC server to be ready..."
          timeout=${{ env.KORA_TIMEOUT }}
          counter=0
          while [ $counter -lt $timeout ]; do
            if curl -s ${{ env.TEST_SERVER_URL }}/health >/dev/null 2>&1; then
              echo "✅ Kora RPC server is ready!"
              break
            fi
            sleep 1
            counter=$((counter + 1))
          done

          if [ $counter -eq $timeout ]; then
            echo "❌ Kora RPC server failed to start within $timeout seconds"
            jobs
            exit 1
          fi

      - name: Setup test environment
        run: |
          echo "🔧 Setting up test environment..."
          cargo run -p tests --bin setup-test-env

      - name: Install cargo-llvm-cov for coverage
        run: cargo install cargo-llvm-cov

      - name: Run integration tests with coverage
        run: |
          echo "🧪 Running integration tests with coverage..."
          # Clean previous coverage data
          cargo llvm-cov clean --workspace

          # Run unit tests with coverage
          echo "Running unit tests with coverage..."
          cargo llvm-cov --workspace --no-report

          # Run integration tests with coverage
          echo "Running integration tests with coverage..."
          cargo llvm-cov --workspace --tests --no-report

          # Generate reports
          echo "Generating coverage reports..."
          mkdir -p coverage
          cargo llvm-cov report --lcov --output-path coverage/lcov.info
          cargo llvm-cov report --html --output-dir coverage/html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Cleanup test environment
        uses: ./.github/actions/cleanup-test-env

      - name: Show failure logs
        uses: ./.github/actions/show-failure-logs
        with:
          test-type: "Rust integration"
          validator-port: ${{ env.VALIDATOR_PORT }}
          kora-port: ${{ env.KORA_RPC_PORT }}