name: TypeScript Integration Tests

on:
  push:
    branches: [main]
    paths:
      # TS SDK changes
      - 'sdks/ts/**'
      # Backend changes that affect TS integration
      - 'crates/**'
      - 'Cargo.*'
      - 'Makefile'
      - '.github/workflows/typescript-integration.yml'

  pull_request:
    branches: [main]
    paths:
      # TS SDK changes  
      - 'sdks/ts/**'
      # Backend changes that affect TS integration
      - 'crates/**'
      - 'Cargo.*'
      - 'Makefile'
      - '.github/workflows/typescript-integration.yml'

env:
  CARGO_TERM_COLOR: always
  # Test environment configuration
  RPC_URL: http://127.0.0.1:8899
  TEST_SERVER_URL: http://127.0.0.1:8080
  KORA_PRIVATE_KEY: 64TVMxZyYyLHwyfZRJUJMqF8GJsMsZQKk4JhdKkyMB7k3fNUjWZdAF1YmyLd43dWEBLCLYjKDkoRGfMwMoGUrDF6
  KORA_CONFIG_FILE: kora.toml
  VALIDATOR_PORT: 8899
  KORA_RPC_PORT: 8080
  VALIDATOR_TIMEOUT: 60
  KORA_TIMEOUT: 30
  RUST_LOG: info

jobs:
  typescript-integration:
    name: TypeScript SDK Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "typescript-integration"
          cache-on-failure: true

      - name: Setup Solana CLI
        uses: ./.github/actions/setup-solana

      - name: Verify Solana CLI installation
        run: |
          echo "Verifying Solana CLI is available for TypeScript tests..."
          solana --version
          solana-test-validator --version
          echo "✅ Solana CLI ready for TypeScript test script"

      - name: Build Kora RPC server
        run: make build

      - name: Start Kora RPC server
        run: |
          echo "🚀 Starting Kora RPC server..."
          cargo run -p kora-rpc --bin kora-rpc -- \
            --private-key ${{ env.KORA_PRIVATE_KEY }} \
            --config ${{ env.KORA_CONFIG_FILE }} \
            --rpc-url ${{ env.RPC_URL }} \
            --port ${{ env.KORA_RPC_PORT }} \
            &
          KORA_PID=$!
          echo "KORA_PID=$KORA_PID" >> $GITHUB_ENV

          # Wait for Kora RPC server to be ready
          echo "⏳ Waiting for Kora RPC server to be ready..."
          timeout=${{ env.KORA_TIMEOUT }}
          counter=0
          while [ $counter -lt $timeout ]; do
            if curl -s ${{ env.TEST_SERVER_URL }}/health >/dev/null 2>&1; then
              echo "✅ Kora RPC server is ready!"
              break
            fi
            sleep 1
            counter=$((counter + 1))
          done

          if [ $counter -eq $timeout ]; then
            echo "❌ Kora RPC server failed to start within $timeout seconds"
            jobs
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.3
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('sdks/ts/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install TypeScript dependencies
        working-directory: sdks/ts
        run: pnpm install --frozen-lockfile

      - name: Build TypeScript SDK
        working-directory: sdks/ts
        run: pnpm build

      - name: Run TypeScript integration tests
        working-directory: sdks/ts
        run: |
          echo "🧪 Running TypeScript SDK integration tests..."
          # The test script handles starting/stopping its own validator
          pnpm test:ci

      - name: Cleanup test environment
        uses: ./.github/actions/cleanup-test-env

      - name: Show failure logs
        uses: ./.github/actions/show-failure-logs
        with:
          test-type: "TypeScript integration"
          validator-port: ${{ env.VALIDATOR_PORT }}
          kora-port: ${{ env.KORA_RPC_PORT }}